name: flutter_network_file_manager
description: A manager to use networkfiles offline.
version: 0.0.2
author: Paul Schunck <p.schunck@silversoft.nl>
homepage: https://github.com/sjoenk/flutter_network_file_manager

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  path: ^1.6.2
  uuid: ^2.0.1
  http: ^0.12.0+2
  sqflite: ^1.1.5
  synchronized: ^2.1.0
  path_provider: ^0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: nl.silversoft.network_file_manager.flutter_network_file_manager
    pluginClass: FlutterNetworkFileManagerPlugin

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
